# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Timestamp')),
                ('units', models.FloatField(verbose_name='Usage')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='UserID')),
                ('area', models.CharField(max_length=2, verbose_name='AreaID')),
                ('tariff', models.CharField(max_length=2, verbose_name='TariffID')),
            ],
        ),
    ]
